server:
  port: 8081
  servlet:
    context-path: /
dubbo:
  application:
    name: customer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan: com.lj.customer.controller  #服务暴露与发现消费所在的package





