server:
  port: 8082
  servlet:
    context-path: /
spring:
 redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
        timeout: 5000
 datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/student
        username: root
        password: zhouyuxiao
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        mybatis:
          type-aliases-package:  com.lj.common.domin

dubbo:
#应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者
  application:
    name: provider
#注册中心配置，用于配置连接注册中心相关信息
  registry:
    address: zookeeper://127.0.0.1:2181
#协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    name: dubbo
    port: 20880
#扫描包
  scan:
    base-packages: com.lj.provider.service.impl

