server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhouyuxiao
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    database: 0
    pool:
      max-active: 10
      max-idle: 8
      max-wait: 100
      min-idle: 2

